// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoparnrblllechukocob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvcGFybnJibGxsZWNodWtvY29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTU0NjgsImV4cCI6MjA2MDkzMTQ2OH0.pEDfVdIhcTHi7ZHvca6g2-rlGLqweqF-JI5lG6yxM14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);